# Generated by Django 2.2.2 on 2019-07-22 20:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryFoodIN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('price', models.FloatField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('main_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_foods_in', to='profile_app.MainUserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryOtherIN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('price', models.FloatField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('main_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_others_in', to='profile_app.MainUserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryOtherOUT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('main_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_others_out', to='profile_app.MainUserProfile')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_others_out', to='inventory.InventoryOtherIN')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryOtherName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(choices=[('kg', 'KG'), ('ltr', 'LTR'), ('pcs', 'PCS')], max_length=5)),
                ('main_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_other_names', to='profile_app.MainUserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='inventoryotherin',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_others_in', to='inventory.InventoryOtherName'),
        ),
        migrations.CreateModel(
            name='InventoryFoodOUT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('main_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_foods_out', to='profile_app.MainUserProfile')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_foods_out', to='inventory.InventoryFoodIN')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryFoodName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(choices=[('kg', 'KG'), ('ltr', 'LTR'), ('pcs', 'PCS')], max_length=5)),
                ('main_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_food_names', to='profile_app.MainUserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='inventoryfoodin',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_foods_in', to='inventory.InventoryFoodName'),
        ),
    ]
