# Generated by Django 2.2.4 on 2019-08-14 01:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_remove_billdata_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='code',
        ),
        migrations.AddField(
            model_name='bill',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
