# Generated by Django 2.2.4 on 2019-08-14 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_auto_20190814_0126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='user',
            new_name='main_user',
        ),
    ]
