# Generated by Django 2.2.4 on 2019-09-14 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='user',
            new_name='main_user',
        ),
    ]
