# Generated by Django 2.2.2 on 2019-07-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuserprofile',
            name='_package',
            field=models.CharField(choices=[('1', 'Basic'), ('2', 'Standard'), ('3', 'Premium')], max_length=55),
        ),
    ]
