# Generated by Django 2.2.4 on 2019-08-14 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billdata',
            name='user',
        ),
    ]
