# Generated by Django 2.2.4 on 2019-09-25 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_auto_20190723_0206'),
        ('bill', '0004_auto_20190814_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='billdata',
            name='main_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bill_data', to='profile_app.MainUserProfile'),
            preserve_default=False,
        ),
    ]
