# Generated by Django 2.2.4 on 2019-10-19 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0005_billdata_main_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billdata',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_bill_data', to='bill.Bill'),
        ),
    ]
